package com.example.tft.navigation

sealed class AppScreens(val route: String) {
    object LoginScreen : AppScreens("Login_Screens")
    object RegisterScreen : AppScreens("Register_Screens")
    object HomeScreen : AppScreens("Home_Screens")
    object UserProfileScreen : AppScreens("Other_Screens/Profile_Screens")
    object EventScreen : AppScreens("Other_Screens/Event_Screens")
    object PilotScreen : AppScreens("Padock_Screen/Pilot_Screens")
    object VideoScreen : AppScreens("Other_Screens/Video_Screens")
    object ForgotPasswordScreen: AppScreens("ForgotPassword_Screen")
    object SeasonDetailScreen : AppScreens("Padock_Screen/Season_Screens/SeasonDetail_Screens")
    object StageDetailScreen : AppScreens("Padock_Screen/Season_Screens/SeasonDetail_Screens/StageDetail_Screens")
    object OtherScreen : AppScreens("Other_Screens")
    object SettingScreen : AppScreens("Other_Screens/Setting_Screens")
    object PilotFavoritesScreen : AppScreens("Other_Screens/PilotFavorites_Screens")
    object FaqScreen: AppScreens("Other_Screens/Faq_Screens")
    object SeasonScreen: AppScreens("Padock_Screen/Season_Screens")
    object CalendarScreen: AppScreens("Other_Screens/Calendar_Screens")
    object GlobalClassificationScreen: AppScreens("Padock_Screen/Season_Screens/GlobalClassification_Screens")
    object SectionsSeasonScreen : AppScreens("SectionsSeason_Screens/{seasonId}")
    object EditProfileScreen : AppScreens("Other_Screens/Profile_Screens/EditProfile_Screens")
    object RouteScreen: AppScreens("Route_Screens")
    object StageDaysDetailScreen : AppScreens("Padock_Screen/Season_Screens/SeasonDetail_Screens/StageDaysDetail_Screens/{stageId}")
    object SectionsStageScreen : AppScreens("SectionsStage_Screens/{stageId}")
    object PilotDetailScreen : AppScreens("Padock_Screen/Pilot_Screens/PilotDetail_Screens/{pilotId}")
    object EventDetailScreen : AppScreens("Home_Screens/EventDetail_Screens/{eventId}")
    object CommunityScreen : AppScreens("Community_Screen")
    object PadockScreen : AppScreens("Padock_Screen")
    object CarCategoriesScreen : AppScreens("Padock_Screen/CarCategories_Screen")
    object CarScreen : AppScreens("Padock_Screen/CarCategories_Screen/carScreen/{categoryId}")

    object PhotosScreen : AppScreens("Other_Screens/Photos_Screen")
    object ForumScreen : AppScreens("Forum_Screen")
    object NewsScreen : AppScreens("News_Screen")
    object NewsDetailScreen : AppScreens("Home_Screens/NewsDetail_Screen/{newsId}")
    object NotificationScreen : AppScreens("Notification_Screen")
    object FilterEventScreen : AppScreens("FilterEvent_Screen")
    object OtherCategoryRallyScreen : AppScreens("OtherCategoryRally_Screen")
    object AllEventsScreen : AppScreens("AllEvents_Screen")
    object CreateQuestionScreen : AppScreens("Community_Screen/CreateQuestion_Screen")
    object QuestionsDetailScreen : AppScreens("Community_Screen/QuestionsDetail_Screen/{questionId}")

    object VotationDetailScreen : AppScreens("Community_Screen/VotationDetail_Screen/{votationId}")

    object TeamWrcScreen : AppScreens("Padock_Screen/TeamWrc_Screen")
    object ChangePasswordScreen : AppScreens("Other_Screens/Profile_Screens/EditProfile_Screens/change_password_screen")
}

