package com.example.tft.navigation

sealed class AppScreens(val route: String) {
    object LoginScreen : AppScreens("Login_Screens")
    object RegisterScreen : AppScreens("Register_Screens")
    object HomeScreen : AppScreens("Home_Screens")
    object UserProfileScreen : AppScreens("Profile_Screens")
    object EventScreen : AppScreens("Event_Screens")
    object PilotScreen : AppScreens("Pilot_Screens")
    object VideoScreen : AppScreens("Video_Screens")
    object ForgotPasswordScreen: AppScreens("ForgotPassword_Screen")
    object SeasonDetailScreen : AppScreens("SeasonDetail_Screens")
    object StageDetailScreen : AppScreens("StageDetail_Screens")
    object OtherScreen : AppScreens("Other_Screens")
    object SettingScreen : AppScreens("Setting_Screens")
    object PilotFavoritesScreen : AppScreens("PilotFavorites_Screens")
    object FaqScreen: AppScreens("Faq_Screens")
    object SeasonScreen: AppScreens("Season_Screens")
    object CalendarScreen: AppScreens("Calendar_Screens")
    object GlobalClassificationScreen: AppScreens("GlobalClassification_Screens")
    object SectionsSeasonScreen : AppScreens("SectionsSeason_Screens/{seasonId}")
    object EditProfileScreen : AppScreens("EditProfile_Screens")
    object RouteScreen: AppScreens("Route_Screens")
    object StageDaysDetailScreen : AppScreens("StageDaysDetail_Screens/{stageId}")
    object SectionsStageScreen : AppScreens("SectionsStage_Screens/{stageId}")
    object PilotDetailScreen : AppScreens("PilotDetail_Screens/{pilotId}")
    object EventDetailScreen : AppScreens("EventDetail_Screens/{eventId}")
    object CommunityScreen : AppScreens("Community_Screen")
    object PadockScreen : AppScreens("Padock_Screen")
    object CarCategoriesScreen : AppScreens("CarCategories_Screen")
    object CarScreen : AppScreens("carScreen/{categoryId}")
    object PhotosScreen : AppScreens("Photos_Screen")
    object ForumScreen : AppScreens("Forum_Screen")
    object NewsScreen : AppScreens("News_Screen")
    object NewsDetailScreen : AppScreens("NewsDetail_Screen")
    object NotificationScreen : AppScreens("Notification_Screen")
    object FilterEventScreen : AppScreens("FilterEvent_Screen")
    object OtherCategoryRallyScreen : AppScreens("OtherCategoryRally_Screen")
    object AllEventsScreen : AppScreens("AllEvents_Screen")
    object CreateQuestionScreen : AppScreens("CreateQuestion_Screen")
    object QuestionsDetailScreen : AppScreens("QuestionsDetail_Screen")
    object VotationDetailScreen : AppScreens("VotationDetail_Screen")
    object TeamWrcScreen : AppScreens("TeamWrc_Screen")
}

